name: ism_mart
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.5+35

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.2
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dialog_flowtter: ^0.3.3
  dotted_border: ^2.0.0+3
  dropdown_search: ^5.0.5
  file_picker: ^6.0.0
  firebase_analytics: ^10.6.3
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_messaging: ^14.7.3
  flutter_countdown_timer: ^4.1.0
  flutter_image_compress: ^2.0.4
  flutter_inappwebview: ^5.7.2+3
  flutter_svg: ^2.0.1
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^4.0.4
  http: ^0.13.1
  iconly: ^1.0.1
  image_picker: ^1.0.0
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  permission_handler: ^10.4.3
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.4
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_new.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^2.0.0
  #build_runner: ^2.3.2
  #freezed: ^2.2.1
  #json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/logo/
    - assets/images/
    - assets/dialog_flow_auth.json
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
